<div class="privacy-main">
  <h1>Privacy Policy</h1>
  <p>Lavoriamo per assicurare che la tua privacy sia protetta ogni volta che utilizzi il nostro sito ed i nostri servizi. A tal fine abbiamo elaborato un’informativa che spiega come vengono utilizzati e protetti i tuoi dati personali</p>
  <p>Trattamento dei Dati Personali <br>I Dati Personali e i Dati di Navigazione (di seguito definiti “Dati”) vengono raccolti automaticamente dal sito web (di seguito: il “Sito”), anche mediante sistemi automatizzati, o a seguito di inserimento volontario dell’Utente o dall’Interessato. I dati sono trattati secondo le modalità di seguito riportate.</p>
  <p>Titolare del Trattamento dei Dati:</p>
  <p>Boolean SRLS <br>Piazzale Giovanni dalle Bande Nere, 9 <br>20146, Milano <br> P.IVA: 10214930967 <br> ciao@boolean.careers</p>
  <p>Tipologie di Dati</p>
  <p>I Dati che potrebbero essere raccolti dal presente Sito sono il nome, il cognome, l’indirizzo, il telefono, l’email, il fax, il codice fiscale, l’indirizzo IP ed altri Dati riferibili alle generalità dell’Utente o alle modalità tecniche di accesso dell’Utente al Sito. Altri dati raccolti per il completamento del profilo di ogni utente (denominato “Studente”) riguardano la propria professionalità ed includono, a titolo esemplificativo: titolo di studio, età, anni di esperienza lavorativa e informazioni curriculari. I Dati di navigazione utili per l’utilizzo tecnico del Sito, sono raccolti necessariamente e il loro conferimento non è facoltativo. Il mancato trattamento di alcuni Dati (es. i dati di contatto, o gli indirizzi, o dati sul comportamento o sulle preferenze dell’utente ecc.) potrebbe rendere impossibile la prestazione dei servizi da parte del Sito. Se l’Utente utilizza il Sito per pubblicare o comunque condividere Dati personali di terzi, (Interessati diversi dall’Utente) ne assume le relative responsabilità. In tal senso, l’Utente garantisce di avere il diritto di comunicare o diffondere i Dati personali dei terzi e di averli previamente informati del trattamento, sollevando il Sito da ogni responsabilità per il loro trattamento strumentale in seguito alla loro comunicazione o diffusione. </p>
  <p>Finalità del Trattamento</p>
  <p>I Dati dell’Utente o dell’Interessato sono raccolti per consentire:</p>
  <p>• l’erogazione del servizio; <br>• la risposta a specifiche richieste informative dell’Utente; <br>• l’aggiornamento dell’Utente sui nuovi prodotti o servizi erogati dal Sito o in relazione a particolari offerte commerciali;<br>• l’informazione dell’Utente in occasione di manutenzione sul Sito o di eventuali disservizi;<br>• l’eventuale profilazione commerciale dell’Utente;<br>• la visualizzazione di banner pubblicitari in relazione agli interessi dell’Utente (behavioral targeting/advertising);<br>• la difesa da parte del Titolare del Sito, in giudizio o nelle fasi propedeutiche alla sua eventuale instaurazione, da abusi<br> nell’utilizzo dello stesso o dei servizi connessi da parte dell’Utente.<br>Alcuni di questi trattamenti (invio di comunicazioni promozionali, profilazione commerciale, behavioral advertising, geolocalizzazione ecc.) potrebbero richiedere il consenso espresso dell’Utente o dell’Interessato. Informative specifiche potrebbero essere presentate nelle pagine del Sito in relazione a particolari servizi o trattamenti dei Dati forniti dall’Utente o dall’Interessato</p>
</div>
